<?php
/**
 * @file
 * structure_front.features.translations_fr.inc
 */

/**
 * Implements hook_translations_fr_defaults().
 */
function structure_front_translations_fr_defaults() {
  $translations = array();
  $translatables = array();
  $translations['fr:default']['2eec6e4857668f0d921dadd82eb35935'] = array(
    'source' => 'Year',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Année',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Year', array(), array('context' => 'interval'));
  $translations['fr:default']['50ccf6e8f54be9378cdbfb9475013252'] = array(
    'source' => 'Hours',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Heures',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Hours', array(), array('context' => 'interval'));
  $translations['fr:default']['6a94230e2f8833073330c0105d069c7b'] = array(
    'source' => 'Hour',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Heure',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Hour', array(), array('context' => 'interval'));
  $translations['fr:default']['6b057f3e5663a13ab3cdb08de16687f0'] = array(
    'source' => 'Years',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Années',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Years', array(), array('context' => 'interval'));
  $translations['fr:default']['8ea5f32288d34edb64fda8a4c9a3eabe'] = array(
    'source' => 'Month',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Mois',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Month', array(), array('context' => 'interval'));
  $translations['fr:default']['8fec7aed2344f13ba62d723b2545c08a'] = array(
    'source' => 'Week',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Semaine',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Week', array(), array('context' => 'interval'));
  $translations['fr:default']['98b763dfcb12ef808fe73739087528ed'] = array(
    'source' => 'Days',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Jours',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Days', array(), array('context' => 'interval'));
  $translations['fr:default']['bc7944ac6bdff5634cf7483d4b2db9d8'] = array(
    'source' => 'Day',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Jour',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Day', array(), array('context' => 'interval'));
  $translations['fr:default']['c8975c4148592e04cfe1f9298ce094e6'] = array(
    'source' => 'Weeks',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Semaines',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Weeks', array(), array('context' => 'interval'));
  $translations['fr:default']['cb1aa0973a8c6f52fa38144fd828bee6'] = array(
    'source' => 'Months',
    'context' => 'interval',
    'location' => '/admin/structure?render=overlay',
    'translation' => 'Mois',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Months', array(), array('context' => 'interval'));
  return $translations;
}
