<?php
/**
 * @file
 * term_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function term_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Son',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '1d69f473-edcd-422d-95cc-2d479c274400',
    'vocabulary_machine_name' => 'popp_tax_content_type',
  );
  $terms[] = array(
    'name' => 'Employés',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '1fd464ce-5ccf-4e40-83d7-ebefde266444',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'Couple sans enfant',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '25250763-34e0-4775-89a1-45b5a986c093',
    'vocabulary_machine_name' => 'popp_tax_family_struc',
  );
  $terms[] = array(
    'name' => 'Panoramique',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '292947df-4a39-420f-98f4-9604382748e7',
    'vocabulary_machine_name' => 'popp_tax_format',
  );
  $terms[] = array(
    'name' => '360*',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '29c66709-df65-4d30-8687-b0ed1ef1c2da',
    'vocabulary_machine_name' => 'popp_tax_format',
  );
  $terms[] = array(
    'name' => 'Agriculteurs',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '4d63c19a-dc26-4025-8ec6-85cb13da1a95',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'CC-*-NC',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '5152db7c-3882-4e6b-8e3c-880c4009517a',
    'vocabulary_machine_name' => 'popp_tax_right',
  );
  $terms[] = array(
    'name' => 'OPP du Pays de Saint Brieuc',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '64e915d5-a329-44dc-b396-5ae699dd40a7',
    'vocabulary_machine_name' => 'popp_tax_thepopp',
  );
  $terms[] = array(
    'name' => 'Vidéo',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '6b0677e3-ab14-4e22-bb11-4eb7ffb46b60',
    'vocabulary_machine_name' => 'popp_tax_content_type',
  );
  $terms[] = array(
    'name' => 'Ouvriers',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '6d2c609c-e816-40d8-8d51-9b6b03b13a63',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'DREAL',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '77c4f827-89f7-4ed8-9563-a259d45656ad',
    'vocabulary_machine_name' => 'popp_tax_thepopp',
  );
  $terms[] = array(
    'name' => 'Intermédiaires',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '7a973557-16d4-473d-a06e-f4cfa62d1f4d',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'Cadre',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '7bddd972-f514-4c52-945a-9acc6c06b680',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'Standard',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '7e71a0f4-678e-4e05-9b87-84d2918c11b3',
    'vocabulary_machine_name' => 'popp_tax_format',
  );
  $terms[] = array(
    'name' => 'Artisans, commerçant et chef d’entreprise',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '832de8d6-4651-492b-859a-b3b7acd691c8',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'Famille monoparentale',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '8cdb5a2a-e0b6-4d1f-91d0-2aac6fb91052',
    'vocabulary_machine_name' => 'popp_tax_family_struc',
  );
  $terms[] = array(
    'name' => 'Photo',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '9b5c3679-2567-4c56-affd-f634b8bceb53',
    'vocabulary_machine_name' => 'popp_tax_content_type',
  );
  $terms[] = array(
    'name' => 'Aménagement',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => '9d954d55-1308-4216-8025-250b2a7feb2a',
    'vocabulary_machine_name' => 'popp_tax_tags',
  );
  $terms[] = array(
    'name' => 'Techniciens, Agents de maîtrise et autres professions',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => 'aeab5044-eee6-4b89-882f-bd7c2c1b25ed',
    'vocabulary_machine_name' => 'popp_tax_sociopro',
  );
  $terms[] = array(
    'name' => 'Célibataire sans enfant',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => 'c0f6d732-5aeb-473e-bbaf-7679e46ea1f3',
    'vocabulary_machine_name' => 'popp_tax_family_struc',
  );
  $terms[] = array(
    'name' => 'Couple avec enfant',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => 'd653059a-6e01-4a1e-b323-0f66d271dc4e',
    'vocabulary_machine_name' => 'popp_tax_family_struc',
  );
  $terms[] = array(
    'name' => 'LGPL',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => 'e0039cf1-f031-45bf-806f-7eff6ed79eda',
    'vocabulary_machine_name' => 'popp_tax_right',
  );
  $terms[] = array(
    'name' => 'Extérieur',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => 'e3a45da3-bb6b-417a-8cf2-2601f2a86654',
    'vocabulary_machine_name' => 'popp_tax_tags',
  );
  $terms[] = array(
    'name' => 'CC-*-ND',
    'description' => '',
    'format' => 'editeur',
    'weight' => 0,
    'uuid' => 'f7eca0e7-49d8-47ee-a299-3f8d52ce0719',
    'vocabulary_machine_name' => 'popp_tax_right',
  );
  return $terms;
}
